version: '3.4'

services:
  ternopildotnet:
    image: ternopildotnet
    build:
      context: .
      dockerfile: TernopilDotNet/Dockerfile
    depends_on:
      - "ternopildotnetmssqlserverdb"
      - "ternopildotnetmysqldb"
    networks:
      - webnet
  ternopildotnetmssqlserverdb:
    image: microsoft/mssql-server-linux:2017-CU8
    ports:
      - "1443:1433"
    environment:
      "ACCEPT_EULA": "Y"
      "SA_PASSWORD": "<YourStrong!Passw0rd>"
    networks:
      - webnet
  ternopildotnetmysqldb:
    image: mysql:8.0.11
    ports:
      - "3306:3306"
    environment:
      "MYSQL_ROOT_PASSWORD": "<YourStrong!Passw0rd>"
    networks:
      - webnet
networks:
  webnet: